---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  dependsOn:
    - name: prometheus-operator-crds
      namespace: monitoring
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "*"
  interval: 24h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controller:
      image:
        pullPolicy: Always
    speaker:
      image:
        pullPolicy: Always
