---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  releaseName: csi-driver-smb
  chart:
    spec:
      chart: csi-driver-smb
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
      version: "*"
  interval: 24h
  # https://github.com/kubernetes-csi/csi-driver-smb/tree/master
  values:
    image:
      smb:
        pullPolicy: Always
      csiProvisioner:
        pullPolicy: Always
      livenessProbe:
        pullPolicy: Always
      nodeDriverRegistrar:
        pullPolicy: Always
      csiproxy:
        pullPolicy: Always
