apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana
  namespace: monitoring
spec:
  provider: vault
  secretObjects:
  - data:
    - key: admin-password
      objectName: password
    - key: admin-user
      objectName: user
    - key: oidc-client-id
      objectName: oidc_client_id
    - key: oidc-client-secret
      objectName: oidc_client_secret
    secretName: grafana
    type: Opaque
