apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      version: "6.15.5"
  # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
  values:
    serviceMonitor:
      enabled: true
      labels:
        release: kubepromstack
      prometheusRule:
        enabled: true
        additionalLabels:
          release: kubepromstack
        rules:
          - alert: PromtailRequestErrors
            expr: 100 * sum(rate(promtail_request_duration_seconds_count{status_code=~"5..|failed"}[1m])) by (namespace, job, route, instance) / sum(rate(promtail_request_duration_seconds_count[1m])) by (namespace, job, route, instance) > 10
            for: 5m
            labels:
              severity: critical
            annotations:
              description: "The {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf \"%.2f\" $value }} errors."
              summary: Promtail request errors (instance {{ $labels.instance }})
          - alert: PromtailRequestLatency
            expr: histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[5m])) by (le)) > 1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: Promtail request latency (instance {{ $labels.instance }})
              description: "The {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf \"%.2f\" $value }}s 99th percentile latency."
