---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system
spec:
  releaseName: secrets-store-csi-driver
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
      version: "*"
  interval: 24h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
# https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/values.yaml
  values:
    nameOverride: secrets-store-csi-driver

    linux:
      image:
        pullPolicy: Always
      crds:
        image:
          pullPolicy: Always
      registrarImage:
        pullPolicy: Always
      livenessProbeImage:
        pullPolicy: Always

    syncSecret:
      enabled: true

    enableSecretRotation: true
    rotationPollInterval: 1h
    providerHealthCheck: true
    providerHealthCheckInterval: 5m
