apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/csi-driver.yaml
  - ../base/ingress-nginx.yaml
  - ../base/cert-manager.yaml
  - ../base/weave-gitops.yaml

resources:
  - metallb-config.yaml

patchesStrategicMerge:
  - csi-driver-values.yaml
  - ingress-nginx-values.yaml
  - cert-manager-values.yaml
