apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
spec:
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "*"
  interval: 2h
  values:
  # https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml
    nameOverride: "mongodb"
    fullnameOverride: "mongodb"

    auth:
      rootPassword: "adminPassword"

    image:
      pullPolicy: Always
