apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/bitnami-repository.yaml
  - ../base/metallb.yaml
  - ../base/csi-drivers/secrets-csi-driver.yaml
  - ../base/csi-drivers/nfs-csi-driver.yaml
  # - ../base/csi-drivers/smb-csi-driver.yaml

patchesStrategicMerge:
  - metallb-values.yaml
  - secrets-csi-driver-values.yaml
  - nfs-csi-driver-values.yaml
  # - smb-csi-driver-values.yaml
