apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  chart:
    spec:
      version: "4.6.0"
  # https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/charts/v4.6.0/csi-driver-nfs/values.yaml
  values:
    controller:
      replicas: 2
