apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  chart:
    spec:
      version: "1.14.0"
  # https://github.com/kubernetes-csi/csi-driver-smb/tree/master
  values:
    controller:
      replicas: 2
